<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MovieManagement.Application\MovieManagement.Application.csproj" />
    <ProjectReference Include="..\MovieManagement.Infrastructure\MovieManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\aspire\MovieManagement.ServiceDefaults\MovieManagement.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
